### PR TITLE
Hello here is a new version with some clean up

### PR DESCRIPTION
**Pull request by frank-dspeed**
Hi my name is Frank Lemanschik i am Senior Lead Developer JavaScript and i want to suggest some changes hope it will help you and you merge them in.
i would also want to add some new functions after this is merged i like the name space and don't want to start a own project.

### CODE REVIEW

**Comment by ReplicaObscura** [comment]
This looks great! I do believe I'll be merging these changes in, but just want to take a little time to go through them. Thanks so much!

**Comment by ReplicaObscura** [comment]
I do think many of these changes are good / moving in the right direction, but there are a couple of big / breaking changes here which need to be thought through and ideally handled separately so that it isn't an all-or-nothing proposal.

These are the separate concerns I see happening in this PR:

- Converting the multiple functions of index.js into a single function (This is the biggest breaking change as it requires anyone who wants to update to change their code. I'm wondering if there's a good reason for removing the helper functions, rather than simply making the helper functions rely on the new "run" function).
- Changing the license to Apache 2.0 (This change is questionable--I chose Unlicense for this project, and I'm curious to understand the reason why you feel it should change. I'm open to the possibility if there's a good enough reason.)
- Bumping the version to 1.0 (I don't think it's ready for a 1.0 release personally, as I'm not ready to commit the final module API yet. Is there a reason this has to bump up to 1.0 for your needs instead of remaining pre-release until it's slightly more mature?)
- Code cleanup (this one's a no-brainer, I'd merge it right away if it were on its own)
- Documentation (also a no-brainer, but obviously the documentation here is specific to the other changes you've made so would have to come after)

Ideally, each of these 5 things should have its own PR so that they can be discussed and merged independently. I realize that's asking kind of a lot, so the other thing I may end up doing is just cherry picking some of the commits from this PR independently, the easiest ones first, and then spending more time with the breaking & license changes.

Thanks again for the efforts, and I'm looking forward to finding the best way to combine our efforts on this.

**Comment by markstos** [comment]
@bmcclure There are no breaking changes here according to the docs, because there was no documented behavior at all. 

@frank-dspeed Have you considered publishing your fork?

**Comment by ReplicaObscura** [comment]
@markstos Documentation aside (I agree, it's sorely needed), there _are_ people using this module, and there are only a handful of functions available from the module. Those are the functions that are already in use. Breaking that arbitrarily doesn't seem like a good way forward.

Publishing the other fork is one option, but why split this functionality into several modules when it would be extremely simple to combine our efforts and include almost all of @frank-dspeed's enhancements, without breaking existing usage.

The only issue is that this is too extensive of a pull request and it breaks things too much for existing users. Simply adding backward-compatible helper functions that call the new generic function would resolve the majority of my concerns, leaving only a debate about the license to be had.

I am of the opinion that including @frank-dspeed's enhancements is absolutely the best way forward, and would be better for everyone (especially npm users) than having such similar modules be maintained separately. I can't think of any good reason to have two forks published of this functionality, unless we simply can't agree on the licensing (and I don't believe that will be an issue).

**Comment by ReplicaObscura** [comment]
I just wanted to mention that I've started cherry picking from this PR and will be committing an update ASAP that will include most of the enhancements and cleanup from @frank-dspeed, as well as documentation similar to what he included.

The license change will likely be all that's left to need a PR for after that.

**Comment by ReplicaObscura** [comment]
I have incorporated some of the items from this PR with a number of changes and additions:

- License has been changed to MIT rather than the proposed Apache 2.0 (I want a copyfree license, but I'm not tied to Unlicense so I think this is a good compromise).
- Existing functionality has been retained, and the new proposed `run` function has been moved to a separate `run` module which is utilized in the main module as well as which can be used directly (see example in the documentation).
- Some code cleanup has been done such as standardizing semicolon usage
- I added an AUTHORS file and a `contributors` property to package.json with your name @frank-dspeed (feel free to contribute a PR that adds an email address and URL to both places if you'd like one listed)
- I updated the proposed documentation, adding back the existing description and changing it to match the latest code.

Due to the extensive nature of the various changes in this PR, I was not able to merge the PR directly and had to simply reference it while making my own updates to the module.

@frank-dspeed, feel free to submit more PRs for additional functions you wish to add to the package, or further enhancements you'd like to make. The quickest way to get your changes merged is if they are small and focused on one specific type of change at a time, but any and all contributions are greatly appreciated.

Thanks for your work on this, and I look forward to any further contributions or suggestions you might have.

**Comment by markstos** [comment]
Thanks for the updates.

**Pull request closed without merging**
